import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "/components/ui/sonner"
import { ThemeProvider } from "/components/theme-provider";

const geistSans = localFont({
 src: "./fonts/GeistVF.woff",
 variable: "--font-geist-sans",
 weight: "100 900",
});
const geistMono = localFont({
 src: "./fonts/GeistMonoVF.woff",
 variable: "--font-geist-mono",
 weight: "100 900",
});

export const metadata = {
 title: "MockMate",
 description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 return (
 <ClerkProvider>
 <html lang="en" suppressHydrationWarning>
 <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
 <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
 <Toaster />
 {children}
 </ThemeProvider>
 </body>
 </html>
 </ClerkProvider>
 );
}
